ShoppingcartProj/Controllers/AddingOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ShoppingcartProj.BL.Entity;
using ShoppingcartProj.BL.IServices;
using ShoppingcartProj.BL.Services;
using ShoppingcartProj.DAL.DbContext;
using ShoppingcartProj.Entity;
using ShoppingcartProj.ViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ShoppingcartProj.Controllers
{
    public class AddingOrderController : Controller
    {
        private readonly IMapper mapper;
        private readonly ICustomerService customerService;
        private readonly IProductService productService;
        private readonly IOrderService orderservice;

        public AddingOrderController(IMapper mapper, ICustomerService customerService,
         IProductService productService, IOrderService orderservice)
        {
            this.mapper = mapper;
            this.customerService = customerService;
            this.productService = productService;
            this.orderservice = orderservice;
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            AddingOrderViewModel model = new AddingOrderViewModel();
            model.CustomerList = mapper.Map<List<CustomerPL>>(customerService.GetCustomers());
            model.productList = mapper.Map<List<ProductPL>>(productService.GetAllProducts());
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCart([FromBody]OrderViewModel modelsave)
        {
            if (ModelState.IsValid)
            { 
                var order = mapper.Map<OrderBL>(modelsave);
                orderservice.AddOrder(order);
            }
            else {

                TempData["Success"] = false;
            }
            return RedirectToAction("Index", "AddingOrder");
        }

        [HttpGet]
        public IActionResult Orderlist()
        {
            OrderlistViewModel orderlist = new OrderlistViewModel();
            orderlist.orderlist = mapper.Map<List<OrderPL>>(orderservice.getAllOrder());
             return View(orderlist);
        }

        [HttpGet]
        public IActionResult OrderDetails(int id)
        {
          var model = mapper.Map<OrderPL>(orderservice.getOrderById(id));
          return View(model);
        }

        [HttpGet]
        public IActionResult updateOrder(int id)
        {
            var model = new updateorderviewmodel();
             model = mapper.Map<updateorderviewmodel>(orderservice.getOrderById(id));
            model.productlist = mapper.Map<List<ProductPL>>(productService.GetAllProducts());
            return View(model);
        }

        [HttpPost]
        public IActionResult saveorder([FromBody]OrderUpdateViewModel orderupdate)
        {
            var updatedorder = mapper.Map<OrderUBL>(orderupdate);
            orderservice.updateorder(updatedorder);
            return RedirectToAction("Orderlist", "AddingOrder");
        }

        [HttpPost]
        public IActionResult deleteorderline([FromBody]int id)
        {
            orderservice.Deleteorderline(id);
            return Ok();
        }

        public IActionResult deleteOrder(int id)
        {

            orderservice.deleteorder(id);
            return RedirectToAction("Orderlist", "AddingOrder");
        }

    }
}

ShoppingcartProj/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ShoppingcartProj.BL.Services;
using ShoppingcartProj.ViewModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ShoppingcartProj.Controllers
{
    public class CustomerController : Controller
    {
        private readonly CustomerService service;
        private readonly IMapper mapper;

        public CustomerController(CustomerService service,IMapper mapper)
        {
            this.service = service;
            this.mapper = mapper;
        }
        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            var model = new AddingOrderViewModel();
            return View(model);
        }
       
    }
}

ShoppingcartProj/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShoppingcartProj.Models;

namespace ShoppingcartProj.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ShoppingcartProj/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using ShoppingcartProj.BL.IServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShoppingcartProj.Controllers
{
    public class ProductController :Controller
    {
        private readonly IProductService productService;
        private readonly IMapper mapper;

        public ProductController(IProductService productService , IMapper mapper)
        {
            this.productService = productService;
            this.mapper = mapper;
        }

    }
}

ShoppingcartProj/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShoppingcartProj.ViewModel;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ShoppingcartProj.Controllers
{
    public class RegisterController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public RegisterController(UserManager<IdentityUser> userManager , SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpPost]
        public async Task<IActionResult> logout() {
            await signInManager.SignOutAsync();
            return RedirectToAction("index","home");


        }


        [HttpGet]
        public IActionResult Register()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid) {
                var user = new IdentityUser { UserName = model.Email,Email = model.Email};
                var result = await userManager.CreateAsync(user, model.password);

                if (result.Succeeded) {
                    await signInManager.SignInAsync(user,isPersistent:false);
                    return RedirectToAction("index","home");

                    }
                foreach (var error in result.Errors) {
                    ModelState.AddModelError("",error.Description);

                }
                
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Login()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {

                var result = await signInManager.PasswordSignInAsync(model.Email,model.Password,model.RememberMe,false);

                if (result.Succeeded)
                {
                   
                    return RedirectToAction("index", "home");

                }
               
                    ModelState.AddModelError(string.Empty, "invalid login attempt");

               

            }

            return View(model);
        }

      /*  [HttpPost]
        public async Task<IActionResult> Logout() {

            await signInManager.SignOutAsync();
            return RedirectToAction("index","home");

        }
        */
    }
}

ShoppingcartProj/Views/AddingOrder/Index.cshtml
@model ShoppingcartProj.ViewModel.AddingOrderViewModel

    <table align="center">

        <tr>
            <td>Customer:</td>
            <td align="center">
                <select class="dropdown" id="Customer-Picker" name="CustomerId" placeholder="customer name" required>
                    <option value="" disabled selected hidden>customer</option>
                    @foreach (var customer in Model.CustomerList)
                    {

                        <option class="dropdown-item" value="@customer.customerId" id="optioncustomer">
                            @customer.Name
                        </option>

                    }

                </select>
            </td>
        </tr>
        <tr>
            <td>Date:</td>

            <td class="form-control">@Html.TextBox("DateCreated", DateTime.Today, new { @readonly = "readonly" })</td>
        </tr>
       

    </table>
        <h3 align="center">Select Item</h3>
        <table align="center">
            <tr>
                <th>Product Name</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Sub Total</th>
                <td></td>
            </tr>
            <tr>
                <td>
                    <select class="dropdown" id="Product-Picker" name="ProdcutId">
                        <option value="" disabled selected hidden >Product</option>
                        @foreach (var product in Model.productList)
                        {
                            <option class="dropdown-item" value="@product.productid" data-unit-price="@product.price"
                                    data-product-description="@product.Description">
                                @product.productName
                            </option>

                        }

                    </select>
                </td>
                <td><p name="ProductDescription" id="desc"></p></td>
                <td><input type="number" min="0"  onchange="calculateTotal()" id="selected-quantity"></td>
                <td><p name="ProductPrice" id="Price"></p></td>
                <td><p name="subtotal" id="subtotal"></p></td>
                <td>
                    <input type="button" id="AddtoOrder" class="btn btn-success" style="position:relative;color:white"
                           value="AddtoOrder"/>
                </td>




            </tr>


        </table>
       
        <table class="table" id="tableporduct" align="center" title="tableporduct">
            <h3 align="center">Order</h3>

            <tbody>
                <th>Product name</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>SubTotal</th>
            </tbody>
            <tbody id="lineitem-container"></tbody>

        </table>
        <div class="text-right">
            <p name="grandtotal" >$<span id="grand-total"></span></p>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-success" id="saveorder" onclick="addorder()">Save</button>
        </div>


<script src="~/js/Order.js"></script>

ShoppingcartProj/Views/AddingOrder/OrderDetails.cshtml
@using ShoppingcartProj.Entity
@model OrderPL
<h1>OrderDetails</h1>


<div class="col">
    <label class="small font-weight-bold">Order Id</label>
    <input type="text" class="form-control form-control-sm" value="@Model.OrderId" disabled />
</div>

<div class="col">
    <label class="small font-weight-bold">Order Date</label>
    <input type="text" class="form-control form-control-sm"
           value="@Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.OrderDate))" disabled />
</div>

<div class="col">
    <label class="small font-weight-bold">Customer Id</label>
    <input type="text" class="form-control form-control-sm" value="@Model.customerId" disabled />

</div>


<div class="col">


    <label class="small font-weight-bold">Order Items</label>
    <table class="table" align="center">
        <tr>
            <th>Product ID</th>
            <th>Quantity</th>
            <th>Unit Price</th>
        </tr>
        @{ 
            var total = 0;
        }
        @foreach (var orderlist in Model.orderItems)
        {
            <tr>
                <td>@orderlist.productid</td>
                <td>@orderlist.Quantity</td>
                <td>@orderlist.UnitPrice</td>
               
            </tr>

            
                
                total = total + (orderlist.UnitPrice * orderlist.Quantity);
            
        }
    </table>

</div>

<div class="col">
    <label class="small font-weight-bold">Grand Total:</label>
    
    <input type="text" class="form-control form-control-sm" value="@total" disabled />

</div>

ShoppingcartProj/Views/AddingOrder/Orderlist.cshtml
@using ShoppingcartProj.ViewModel
@model OrderlistViewModel

<h3>Orderlist</h3>
<table class="table" align="center">
    <tr>
        <th>Order ID</th>
        <th>Customer ID</th>
        <th>Order Date</th>
       
        <th>Order Item count</th>
        <th></th>

    </tr>
    <tbody>
       
     
        @foreach (var orderlist in Model.orderlist)
        {
        <tr>
            <td>@orderlist.OrderId</td>
            <td>@orderlist.customerId</td>

            <td>@Convert.ToString(string.Format("{0:dd/MM/yyyy}", orderlist.OrderDate))</td>
            <td ><p align="center">@orderlist.orderItems.Count()</p></td>


            <td>


                @Html.ActionLink("Details", "OrderDetails", new { Id = orderlist.OrderId }) |
                @Html.ActionLink("Edit", "updateOrder", new { Id = orderlist.OrderId }) |
                @Html.ActionLink("Delete", "deleteOrder", new { Id = orderlist.OrderId }) |



            </td>

        </tr>
        }

    </tbody>

</table>

ShoppingcartProj/Views/AddingOrder/updateOrder.cshtml
@using ShoppingcartProj.ViewModel
@model updateorderviewmodel


<h1 align="center">updateOrder</h1>
<div align="center">
    <div class="col">
        <label class="small font-weight-bold">Order Id</label>
        <input type="text" id="updateorderid" value="@Model.OrderId" disabled />
    </div>

    <div class="col">
        <label class="small font-weight-bold">Order Date</label>
        <input type="text" id="updatedate"
               value="@Model.OrderDate" disabled />
    </div>

    <div class="col">
        <label class="small font-weight-bold">Customer Id</label>
        <input type="text" id="updatecustomerid" value="@Model.customerId" disabled />

    </div>
</div>
<div class="col">

    <div class="addnewitem">
        <table align="center" class="table">
            <thead>
                <tr>
                    <th> Product ID</th>

                    <th>Description</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Available</th>
                    <th>Sub Total</th>
                    <th></th>

                </tr>
            </thead>
            <tbody>
                <tr>

                    <td>
                        <select class="dropdown" id="Product-Picker" name="ProdcutId">
                            <option class="dropdown-item">Product</option>
                            @foreach (var product in Model.productlist)
                            {
                                <option class="dropdown-item" value="@product.productid" data-unit-price="@product.price"
                                        data-product-description="@product.Description" data-avaliable-quantity="@product.Quantity">
                                    @product.productName
                                </option>

                            }

                        </select>
                    </td>
                    <td><p name="productdesc" id="desc"></p></td>
                    <td>
                        @*<input type="number" [max]="limit" min="0" onchange="calculateTotal()"  id="selected-quantity">*@
                        <p>
                        <p>
                            <input type="button" class="minus" onclick="calculateTotal()" value="-" />
                            <input type="text" id="selected-quantity" @*onchange="calculateTotal()"*@ readonly="readonly" />
                            <input type="button" class="plus" onclick="calculateTotal()" value="+" />

                        </p>

                        </p>
                    </td>
                    <td><p name="ProductPrice" id="Price"></p></td>
                    <td><p name="ProductAvailable" id="available"></p></td>
                    <td><input type="text" id="subtotal" disabled /></td>
                    <td>
                        <input type="button" id="AddtoOrder" class="btn btn-success" style="position:relative;color:white"
                               value="Add" />
                    </td>

                </tr>
            </tbody>
        </table>
    </div>
    <p id="itemCount" hidden>@Model.orderItems.Count()</p>
    <label class="small font-weight-bold">Order Items</label>
    <table class="table" align="center">
        <tr>
            <th>Product ID</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Sub Total</th>
            <th></th>
        </tr>

        <tbody id="updateorderBody">
            @foreach (var orderlist in Model.orderItems)
            {
                <tr>
                    <td><input type="text" id="updateproductid" value="@orderlist.productid" disabled /></td>
                    <td><input type="text" id="updatedqty" min="0" oninput="calculateupdateprice();" value="@orderlist.Quantity" /></td>
                    <td><input type="text" id="unitprice" value="@orderlist.UnitPrice" disabled /></td>

                    <td><input type="text" id="subtotal" disabled /></td>

                    <td>
                        <input type="button" name="Delete" value="Delete"
                               onclick="removeRow(this,@orderlist.OrderItemId,
                                            @orderlist.productid,@orderlist.Quantity,@orderlist.UnitPrice);" />
                      
                    </td>
                    <td><input type="text" id="lineitemid" value="@orderlist.OrderItemId" disabled /></td>
                </tr>



                //  total = total + (ordalseerlist.subtotal);

            }


        </tbody>

    </table>@*removeorderline(@orderlist.OrderItemId);*@

</div>
<div align="center">
    <button id="update" onclick="updateorder();">Update</button>
    <button id="cancel" onclick=" redirectOnClick();">Cancel</button>
</div>

<script src='https://code.jquery.com/jquery-3.1.0.min.js'></script>
<script type='text/javascript' src="~/js/edit.js"></script>

ShoppingcartProj/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ShoppingcartProj/Views/Register/Login.cshtml
@using ShoppingcartProj.ViewModel
@model LoginViewModel

@{ 
    ViewBag.Title = "User Login";

}

<h1>User Login</h1>
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label asp-for="RememberMe">
                        <input asp-for="RememberMe"/>
                        @Html.DisplayNameFor(m => m.RememberMe)
                    </label>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">login </button>

        </form>
    </div>

</div>

ShoppingcartProj/Views/Register/Register.cshtml
@using ShoppingcartProj.ViewModel
@model RegisterViewModel

@{
    ViewBag.Title = "User Registration";
}

<h1>User Register</h1>

<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="password"></label>
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="confirmpassword"></label>
                <input asp-for="confirmpassword" class="form-control" />
                <span asp-validation-for="confirmpassword" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-outline-primary">Register</button>
        </form>

    </div>
</div>

ShoppingcartProj/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingcartProj</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingcartProj</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav ml-auto">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AddingOrder"
                                   asp-action="Index">Order</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AddingOrder"
                                   asp-action="Orderlist">OrderList</a>
                            </li>


                            <li class="nav-item">
                                <form method="post" asp-action="Logout" asp-controller="register">
                                    <button type="submit" class="nav-link btn btn-link py-0"
                                            style="width:auto">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>


                        }
                        else
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register"
                                   asp-action="register">Register</a>
                            </li>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register"
                                   asp-action="login">login</a>
                            </li>



                        }





                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="privacy">Privacy</a>
                        </li>


                    </ul>



                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ShoppingcartProj - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>